version: "3.9"
services:
  api:
    build: ./app 
    container_name: ml_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
  
  streamlit:
    build: ./app
    container_name: ml_ui
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - api